# Generated by Django 5.0.6 on 2024-05-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groupLIST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('Desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='todoLIST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('Desc', models.CharField(max_length=200)),
                ('Deadline', models.DateField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.grouplist')),
            ],
        ),
        migrations.CreateModel(
            name='taskLIST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=100)),
                ('Flag', models.BooleanField()),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
            ],
        ),
    ]
