# Generated by Django 5.0.6 on 2024-05-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplist',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='grouplist',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='grouplist',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='Flag',
            new_name='flag',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Deadline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Name',
            new_name='name',
        ),
    ]
