# Generated by Django 5.0.6 on 2024-05-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_desc_grouplist_desc_rename_id_grouplist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplist',
            name='desc',
        ),
    ]
