# Generated by Django 5.0.6 on 2024-05-31 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_grouplist_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='group',
        ),
        migrations.DeleteModel(
            name='groupLIST',
        ),
    ]
