# Generated by Django 5.0.6 on 2024-05-31 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todolist_group_delete_grouplist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='taskLIST',
        ),
    ]
